function postAcq
% default post acquisition function. 
%
% function postAcq
%
% You may write your own and have it run via the INI file. 
% It should take no input arguments.
% Place your post-acquisition file in your MATLAB path but 
% not in the StitchIt install, or you will run into problems
% pulling changes. 
%
% Do not edit this file unless you know what you're doing.
%
% Rob Campbell - Basel 2015


M=readMetaData2Stitchit;

%check for and fix missing tiles if this was a TissueCyte acquisition
if strcmp(M.System.type,'TissueCyte')
    missingTiles=identifyMissingTilesInDir('rawData',0);
else
    missingTiles = -1;
end

if iscell(missingTiles) && ~isempty(missingTiles)
    fname='missingTiles.mat';
    fprintf('Found and fixed %d missing tiles. Saving missing tile list to %s\n', ...
        length(missingTiles), fname);
    save(fname,'missingTiles')
elseif iscell(missingTiles) && isempty(missingTiles)
    fprintf('Searched for missing tiles but did not find any\n')
elseif ~iscell(missingTiles) && missingTiles == -1
    %nothing happens. No TissueCyte.
end


%-----------------------------------------------------
%attempt to stitch all the data
stitchAllSubDirectories
%-----------------------------------------------------



if exist('generate_MaSIV_list','file')
    fprintf('Making MaSIV section list\n')
    generate_MaSIV_list('stitchedImages_100')
else
    fprintf('Could not find generate_MaSIV_list. SKIPPING\n')
end

